version: '3.8'

volumes:
  elasticdata:


services:

  nginx:
    image: nginx:1.23.1
    restart: always
    ports:
      - target: 443
        published: 443
        mode: host
      - target: 80
        published: 80
        mode: host
    volumes:
      - ./conf/nginx/conf/default-dev.conf:/etc/nginx/conf.d/default-dev.conf
      - ./conf/nginx/certs:/etc/nginx/certs
    logging:
      driver: "none"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: ./backend.dockerfile
    restart: always
    volumes:
      - ./backend/backend:/backend/
    ports:
      - "8000:8000"
    env_file:
      - .env

  celery_backend:
    build:
      context: ./backend
      dockerfile: ./celery.dockerfile
    restart: always
    volumes:
      - ./backend/backend:/backend/
    env_file:
      - .env
    depends_on:
      - backend
      - redis

  websocket:
    build:
      context: ./websocket
      dockerfile: ./websocket.dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ./websocket/websocket_app:/websocket_app
    ports:
      - "8001:8000"

  redis:
    image: redis:7.0.0
    restart: always
    # logging:
    #   driver: none
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 3s

  elastic:
    image: elasticsearch:8.4.2
    restart: always
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
    mem_limit: 2g
    healthcheck:
      test: curl -fs http://127.0.0.1:9200/_cat/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
# -------------------------------------------------------------------------------------------------