# Generated by Django 4.1.1 on 2022-10-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subscribechannel_user_and_channel_uniq'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscribechannel',
            name='user_and_channel_uniq',
        ),
        migrations.AddConstraint(
            model_name='likevideo',
            constraint=models.UniqueConstraint(fields=('user', 'video'), name='user_and_video_unique'),
        ),
        migrations.AddConstraint(
            model_name='subscribechannel',
            constraint=models.UniqueConstraint(fields=('user', 'channel'), name='user_and_channel_unique'),
        ),
    ]
