# Generated by Django 4.1.1 on 2022-10-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_subscribechannel_user_and_channel_uniq_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='elastic_id',
        ),
    ]
