# Generated by Django 4.1.3 on 2022-11-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_video_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='imagekit_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
