# Generated by Django 4.1.1 on 2022-10-13 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_video_elastic_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
