# Generated by Django 4.1.3 on 2022-11-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_video_imagekit_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='imagekit_url',
        ),
    ]
