name: Project Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Start all services
      run: docker-compose up --build -d


  testing:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: Start backend test
      run: docker exec videohosting_backend_1 bash -c "python3 manage.py test"
