name: Project Testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Start all services and testing
      run: |
        docker-compose up --build -d
        docker exec videohosting_backend_1 bash -c "python3 manage.py test"
